import { ObjectId } from "mongodb";
import getMongoClient from "@/lib/mongodb";

export type ResearchCategory =
  | "market_trends"
  | "comparable_productions"
  | "talent"
  | "audience"
  | "industry_developments"
  | "general_research";

export interface RawSearchResult {
  title: string;
  url: string;
  snippet: string;
}

export interface CompetitorOrComp {
  title: string;
  metrics?: string;
  relevance: string;
}

export interface ResearchAIAnalysis {
  executiveSummary: string;
  keyFindings: string[];
  marketOpportunities: string[];
  competitorsOrComps: CompetitorOrComp[];
  strategicRecommendations: string[];
  riskFactors: string[];
}

export interface ResearchResult {
  _id?: ObjectId;

  /**
   * Project this research report belongs to.
   */
  projectId: ObjectId;

  /**
   * User who initiated the research query.
   */
  userId: string;

  /**
   * Specific domain or category of the research.
   */
  category: ResearchCategory;

  /**
   * Prompt or objective query submitted by the user.
   */
  objective: string;

  /**
   * Live external search results retrieved via Parallel API.
   */
  rawSearchResults: RawSearchResult[];

  /**
   * Gemini synthesized intelligence report.
   */
  aiAnalysis: ResearchAIAnalysis;

  /**
   * Timestamps.
   */
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Returns the MongoDB research_results collection.
 */
export async function getResearchResultsCollection() {
  const client = await getMongoClient();
  const db = client.db();

  return db.collection<ResearchResult>("research_results");
}

let indexesEnsured = false;
let indexPromise: Promise<void> | null = null;

/**
 * Ensures all required research results indexes exist.
 */
export async function ensureResearchResultIndexes(): Promise<void> {
  if (indexesEnsured) {
    return;
  }

  if (!indexPromise) {
    indexPromise = getResearchResultsCollection()
      .then(async (results) => {
        /**
         * Efficiently retrieve research history for a project by creation date.
         */
        await results.createIndex(
          {
            projectId: 1,
            createdAt: -1,
          },
          {
            name: "research_results_project_created_at",
          }
        );

        /**
         * Filter research results by category within a project.
         */
        await results.createIndex(
          {
            projectId: 1,
            category: 1,
          },
          {
            name: "research_results_project_category",
          }
        );

        /**
         * Retrieve research reports generated by a specific user.
         */
        await results.createIndex(
          {
            userId: 1,
            createdAt: -1,
          },
          {
            name: "research_results_user_created_at",
          }
        );
      })
      .catch((error) => {
        indexPromise = null;
        throw error;
      });
  }

  await indexPromise;
  indexesEnsured = true;
}